// Angular/project-app/src/app/login/login.component.ts
// login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(private router: Router) { }

  ngOnInit(): void {
  }

  login() {
    // Perform login logic here (e.g., send request to server)
    // For simplicity, let's assume login is successful
    this.router.navigate(['/home']);
  }

}

<!-- login.component.html -->
<div class="login-container">
    <h2>Login</h2>
    <form (ngSubmit)="login()" #loginForm="ngForm">
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" id="username" name="username" ngModel required>
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" id="password" name="password" ngModel required>
      </div>
      <button type="submit" [disabled]="!loginForm.valid">Login</button>
    </form>
  </div>

// React/poco-website/src/Login.js
 import React, { Component } from "react";
 import "./LoginStyle.css";

 export class Login extends Component {
     render() {
         return (
             <div className="body">
                <div class="container">
                    <form class="login-form" id="loginForm">
                        <h2>Login to Poco Mobiles Community</h2>
                        <div class="input-group">
                            <label for="username">Username</label>
                            <input type="text" id="username" name="username" required/>
                        </div>
                        <div class="input-group">
                            <label for="password">Password</label>
                            <input type="password" id="password" name="password" required/>
                        </div>
                        <button type="submit">LOGIN</button>
                        <div class="extra-links">
                            <a href="#">Forgot Password?</a>
                            <a href="#">Create Account</a>
                        </div>
                    </form>
                </div>

             </div>
         )
     }
 }

 export default Login
